title: "Сознание, тело, язык"
subtitle: "Философские традиции Востока и Запада о природе восприятия"
description: "Опорные материалы к лекции «Сознание, тело, язык в истории западноевропейской мысли»"
baseurl: ""
url: "http://localhost:4000"
lang: ru

collections:
  sections:
    output: true
    permalink: /lecture/:name/
  sections2:
    output: true
    permalink: /lecture2/:name/
  philosophers_all:
    output: true
    permalink: /philosopher/:name/

defaults:
  - scope:
      path: ""
      type: "sections"
    values:
      layout: "section"
  - scope:
      path: ""
      type: "sections2"
    values:
      layout: "section2"
  - scope:
      path: ""
      type: "philosophers_all"
    values:
      layout: "philosopher-page"

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM

sass:
  style: compressed

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
